#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : stoken
Version  : 0.92
Release  : 2
URL      : https://github.com/cernekee/stoken/archive/v0.92.tar.gz
Source0  : https://github.com/cernekee/stoken/archive/v0.92.tar.gz
Summary  : Software token
Group    : Development/Tools
License  : BSD-3-Clause LGPL-2.1
Requires: stoken-bin = %{version}-%{release}
Requires: stoken-data = %{version}-%{release}
Requires: stoken-lib = %{version}-%{release}
Requires: stoken-license = %{version}-%{release}
Requires: stoken-man = %{version}-%{release}
BuildRequires : gmp-dev
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(hogweed)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(nettle)

%description
Description:
This directory contains a JNI interface layer for libstoken, and a
demo program to show how it can be used.

%package bin
Summary: bin components for the stoken package.
Group: Binaries
Requires: stoken-data = %{version}-%{release}
Requires: stoken-license = %{version}-%{release}

%description bin
bin components for the stoken package.


%package data
Summary: data components for the stoken package.
Group: Data

%description data
data components for the stoken package.


%package dev
Summary: dev components for the stoken package.
Group: Development
Requires: stoken-lib = %{version}-%{release}
Requires: stoken-bin = %{version}-%{release}
Requires: stoken-data = %{version}-%{release}
Provides: stoken-devel = %{version}-%{release}
Requires: stoken = %{version}-%{release}

%description dev
dev components for the stoken package.


%package doc
Summary: doc components for the stoken package.
Group: Documentation
Requires: stoken-man = %{version}-%{release}

%description doc
doc components for the stoken package.


%package lib
Summary: lib components for the stoken package.
Group: Libraries
Requires: stoken-data = %{version}-%{release}
Requires: stoken-license = %{version}-%{release}

%description lib
lib components for the stoken package.


%package license
Summary: license components for the stoken package.
Group: Default

%description license
license components for the stoken package.


%package man
Summary: man components for the stoken package.
Group: Default

%description man
man components for the stoken package.


%prep
%setup -q -n stoken-0.92

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1560442500
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1560442500
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/stoken
cp COPYING.LIB %{buildroot}/usr/share/package-licenses/stoken/COPYING.LIB
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/stoken
/usr/bin/stoken-gui

%files data
%defattr(-,root,root,-)
/usr/share/applications/stoken-gui-small.desktop
/usr/share/applications/stoken-gui.desktop
/usr/share/pixmaps/stoken-gui.png
/usr/share/stoken/password-dialog.ui
/usr/share/stoken/pin-dialog.ui
/usr/share/stoken/tokencode-detail.ui
/usr/share/stoken/tokencode-small.ui

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libstoken.so
/usr/lib64/pkgconfig/stoken.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/stoken/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libstoken.so.1
/usr/lib64/libstoken.so.1.3.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/stoken/COPYING.LIB

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/stoken-gui.1
/usr/share/man/man1/stoken.1
